---
openapi: 3.0.2
info:
  title: Stock API
  version: 1.0.0
  description: Stock API for https://github.com/redhat-france-sa/microservices-saga-blueprint
paths:
  /stock/reserve:
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductItem'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductItem'
          description: Reserved product items
      operationId: ReserveProducts
      summary: Reserver products
  /stock/release:
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProductItem'
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductItem'
          description: Released product items
      operationId: ReleaseProducts
      summary: Release products
  /stock/{id}/check:
    get:
      parameters:
      - name: id
        description: Product identifier
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuantityInfo'
          description: Product and quantity is available
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuantityInfo'
          description: Product in quantity is not available
      operationId: CheckProductStock
      summary: Check stock for product
    parameters:
    - name: id
      description: Product identifier
      schema:
        type: string
      in: path
      required: true
    - name: quantity
      description: ""
      schema:
        type: integer
      in: query
      required: true
components:
  schemas:
    QuantityInfo:
      description: ""
      required:
      - quantity
      type: object
      properties:
        quantity:
          description: ""
          type: integer
    ProductItem:
      $ref: apicurio:54890#/components/schemas/ProductItem
