kind: Secret
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: stock-database
  labels:
    app: stock-database
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: stock-database
stringdata:
  database-name: ordersdb
  database-password: wOUU1yisdoJLPmvG
  database-user: userIUO
type: Opaque
---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"dbz-postgresql:latest","namespace":"microsaga-order"},"fieldPath":"spec.template.spec.containers[?(@.name==\"stock-database\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  name: stock-database
  labels:
    app: stock-database
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: stock-database
    app.kubernetes.io/part-of: stock-service-app
    app.openshift.io/runtime: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-database
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stock-database
        deploymentconfig: stock-database
    spec:
      containers:
        - name: stock-database
          image: >-
            image-registry.openshift-image-registry.svc:5000/microsaga-infra/debezium-postgresql:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stock-database
                  key: database-password
            - name: DATABASE_SERVICE_NAME
              value: stock-database
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: stock-database
                  key: database-name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: stock-database
                  key: database-user
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: postgrespw
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600