/*
 * Order API
 * Order API for https://github.com/redhat-france-sa/microservices-saga-blueprint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.microsaga.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * OrderInfo
 */
public class OrderInfo {

  private String customerId;


  private List<ProductItem> productItems = new ArrayList<ProductItem>();


  private Double totalPrice;

  
  private String currency;


  private String paymentCardId;


  private String shippingAddressId;

  public OrderInfo() {}


   /**
   * Get customerId
   * @return customerId
   **/

  public String getCustomerId() {
    return customerId;
  }


  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }




  public void addProductItemsItem(ProductItem productItemsItem) {
    this.productItems.add(productItemsItem);
  }

   /**
   * Get productItems
   * @return productItems
  **/


  public List<ProductItem> getProductItems() {
    return productItems;
  }


  public void setProductItems(List<ProductItem> productItems) {
    this.productItems = productItems;
  }



   /**
   * Get totalPrice
   * @return totalPrice
   **/


  public Double getTotalPrice() {
    return totalPrice;
  }


  public void setTotalPrice(Double totalPrice) {
    this.totalPrice = totalPrice;
  }


   /**
   * Get currency
   * @return currency
   **/

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }

   /**
   * Get paymentCardId
   * @return paymentCardId
   **/

  public String getPaymentCardId() {
    return paymentCardId;
  }


  public void setPaymentCardId(String paymentCardId) {
    this.paymentCardId = paymentCardId;
  }


   /**
   * Get shippingAddressId
   * @return shippingAddressId
  **/

  public String getShippingAddressId() {
    return shippingAddressId;
  }


  public void setShippingAddressId(String shippingAddressId) {
    this.shippingAddressId = shippingAddressId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderInfo orderInfo = (OrderInfo) o;
    return Objects.equals(this.customerId, orderInfo.customerId) &&
        Objects.equals(this.productItems, orderInfo.productItems) &&
        Objects.equals(this.totalPrice, orderInfo.totalPrice) &&
        Objects.equals(this.currency, orderInfo.currency) &&
        Objects.equals(this.paymentCardId, orderInfo.paymentCardId) &&
        Objects.equals(this.shippingAddressId, orderInfo.shippingAddressId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, productItems, totalPrice, currency, paymentCardId, shippingAddressId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderInfo {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    productItems: ").append(toIndentedString(productItems)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    paymentCardId: ").append(toIndentedString(paymentCardId)).append("\n");
    sb.append("    shippingAddressId: ").append(toIndentedString(shippingAddressId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

