FROM registry.redhat.io/amq7/amq-streams-kafka-28-rhel8:1.8.0
USER root:root
COPY ./debezium-plugins/ /opt/kafka/plugins/
COPY kafka-connect-expand-json-payload-smt-0.0.1-assemble-all.jar /opt/kafka/plugins/kafka-connect-expand-json-payload-smt-0.0.1-assemble-all.jar
USER 1001